/*
NetBox REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.0.11 (4.0)
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package netbox

import (
	"encoding/json"
)

// checks if the BriefCustomFieldChoiceSetRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BriefCustomFieldChoiceSetRequest{}

// BriefCustomFieldChoiceSetRequest Extends the built-in ModelSerializer to enforce calling full_clean() on a copy of the associated instance during validation. (DRF does not do this by default; see https://github.com/encode/django-rest-framework/issues/3144)
type BriefCustomFieldChoiceSetRequest struct {
	Name                 *string `json:"name,omitempty"`
	Description          *string `json:"description,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _BriefCustomFieldChoiceSetRequest BriefCustomFieldChoiceSetRequest

// NewBriefCustomFieldChoiceSetRequest instantiates a new BriefCustomFieldChoiceSetRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBriefCustomFieldChoiceSetRequest() *BriefCustomFieldChoiceSetRequest {
	this := BriefCustomFieldChoiceSetRequest{}
	return &this
}

// NewBriefCustomFieldChoiceSetRequestWithDefaults instantiates a new BriefCustomFieldChoiceSetRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBriefCustomFieldChoiceSetRequestWithDefaults() *BriefCustomFieldChoiceSetRequest {
	this := BriefCustomFieldChoiceSetRequest{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *BriefCustomFieldChoiceSetRequest) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BriefCustomFieldChoiceSetRequest) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *BriefCustomFieldChoiceSetRequest) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *BriefCustomFieldChoiceSetRequest) SetName(v string) {
	o.Name = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *BriefCustomFieldChoiceSetRequest) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BriefCustomFieldChoiceSetRequest) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *BriefCustomFieldChoiceSetRequest) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *BriefCustomFieldChoiceSetRequest) SetDescription(v string) {
	o.Description = &v
}

func (o BriefCustomFieldChoiceSetRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BriefCustomFieldChoiceSetRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *BriefCustomFieldChoiceSetRequest) UnmarshalJSON(data []byte) (err error) {
	varBriefCustomFieldChoiceSetRequest := _BriefCustomFieldChoiceSetRequest{}

	err = json.Unmarshal(data, &varBriefCustomFieldChoiceSetRequest)

	if err != nil {
		return err
	}

	*o = BriefCustomFieldChoiceSetRequest(varBriefCustomFieldChoiceSetRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "name")
		delete(additionalProperties, "description")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableBriefCustomFieldChoiceSetRequest struct {
	value *BriefCustomFieldChoiceSetRequest
	isSet bool
}

func (v NullableBriefCustomFieldChoiceSetRequest) Get() *BriefCustomFieldChoiceSetRequest {
	return v.value
}

func (v *NullableBriefCustomFieldChoiceSetRequest) Set(val *BriefCustomFieldChoiceSetRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableBriefCustomFieldChoiceSetRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableBriefCustomFieldChoiceSetRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBriefCustomFieldChoiceSetRequest(val *BriefCustomFieldChoiceSetRequest) *NullableBriefCustomFieldChoiceSetRequest {
	return &NullableBriefCustomFieldChoiceSetRequest{value: val, isSet: true}
}

func (v NullableBriefCustomFieldChoiceSetRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBriefCustomFieldChoiceSetRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
