/*
NetBox REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.0.11 (4.0)
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package netbox

import (
	"encoding/json"
)

// checks if the BriefVirtualChassisRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BriefVirtualChassisRequest{}

// BriefVirtualChassisRequest Adds support for custom fields and tags.
type BriefVirtualChassisRequest struct {
	Name                 *string                     `json:"name,omitempty"`
	Master               NullableNestedDeviceRequest `json:"master,omitempty"`
	Description          *string                     `json:"description,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _BriefVirtualChassisRequest BriefVirtualChassisRequest

// NewBriefVirtualChassisRequest instantiates a new BriefVirtualChassisRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBriefVirtualChassisRequest() *BriefVirtualChassisRequest {
	this := BriefVirtualChassisRequest{}
	return &this
}

// NewBriefVirtualChassisRequestWithDefaults instantiates a new BriefVirtualChassisRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBriefVirtualChassisRequestWithDefaults() *BriefVirtualChassisRequest {
	this := BriefVirtualChassisRequest{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *BriefVirtualChassisRequest) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BriefVirtualChassisRequest) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *BriefVirtualChassisRequest) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *BriefVirtualChassisRequest) SetName(v string) {
	o.Name = &v
}

// GetMaster returns the Master field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BriefVirtualChassisRequest) GetMaster() NestedDeviceRequest {
	if o == nil || IsNil(o.Master.Get()) {
		var ret NestedDeviceRequest
		return ret
	}
	return *o.Master.Get()
}

// GetMasterOk returns a tuple with the Master field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BriefVirtualChassisRequest) GetMasterOk() (*NestedDeviceRequest, bool) {
	if o == nil {
		return nil, false
	}
	return o.Master.Get(), o.Master.IsSet()
}

// HasMaster returns a boolean if a field has been set.
func (o *BriefVirtualChassisRequest) HasMaster() bool {
	if o != nil && o.Master.IsSet() {
		return true
	}

	return false
}

// SetMaster gets a reference to the given NullableNestedDeviceRequest and assigns it to the Master field.
func (o *BriefVirtualChassisRequest) SetMaster(v NestedDeviceRequest) {
	o.Master.Set(&v)
}

// SetMasterNil sets the value for Master to be an explicit nil
func (o *BriefVirtualChassisRequest) SetMasterNil() {
	o.Master.Set(nil)
}

// UnsetMaster ensures that no value is present for Master, not even an explicit nil
func (o *BriefVirtualChassisRequest) UnsetMaster() {
	o.Master.Unset()
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *BriefVirtualChassisRequest) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BriefVirtualChassisRequest) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *BriefVirtualChassisRequest) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *BriefVirtualChassisRequest) SetDescription(v string) {
	o.Description = &v
}

func (o BriefVirtualChassisRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BriefVirtualChassisRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if o.Master.IsSet() {
		toSerialize["master"] = o.Master.Get()
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *BriefVirtualChassisRequest) UnmarshalJSON(data []byte) (err error) {
	varBriefVirtualChassisRequest := _BriefVirtualChassisRequest{}

	err = json.Unmarshal(data, &varBriefVirtualChassisRequest)

	if err != nil {
		return err
	}

	*o = BriefVirtualChassisRequest(varBriefVirtualChassisRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "name")
		delete(additionalProperties, "master")
		delete(additionalProperties, "description")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableBriefVirtualChassisRequest struct {
	value *BriefVirtualChassisRequest
	isSet bool
}

func (v NullableBriefVirtualChassisRequest) Get() *BriefVirtualChassisRequest {
	return v.value
}

func (v *NullableBriefVirtualChassisRequest) Set(val *BriefVirtualChassisRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableBriefVirtualChassisRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableBriefVirtualChassisRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBriefVirtualChassisRequest(val *BriefVirtualChassisRequest) *NullableBriefVirtualChassisRequest {
	return &NullableBriefVirtualChassisRequest{value: val, isSet: true}
}

func (v NullableBriefVirtualChassisRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBriefVirtualChassisRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
