---
name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0

      - name: Release
        uses: softprops/action-gh-release@v0.1.15
        with:
          generate_release_notes: true
